
# MySQL数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    username: xxx
    password: xxx

mybatis:
  #配置MyBatis的xml配置文件路径
  mapper-locations: classpath:com.isliujiao.projectdemo.mapper/*.xml
  #配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.isliujiao.projectdemo

server:
  port: 8090

